version: 2
project_name: reliquary

release:
  github:
    owner: SentimentalK
    name: reliquary-releases

builds:
  - binary: reliquary
    dir: client
    main: ./cmd
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    hooks:
      post:
        - sh -c "if [[ '{{ .Os }}' == 'darwin' ]]; then codesign --force --deep -s - {{ .Path }}; fi"
    overrides:
      - goos: windows
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: SentimentalK
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    
    name: reliquary
    
    homepage: "https://github.com/SentimentalK/Reliquary"
    description: "Reliquary: Your Digital Phylactery."
    license: "Private" 

scoops:
  - repository:
      owner: SentimentalK
      name: scoop-bucket
      token: "{{ .Env.GH_PAT }}"
    
    name: reliquary
    homepage: "https://github.com/SentimentalK/Reliquary"
    description: "Reliquary: Your Digital Phylactery."
    license: "Private"